version: '3.8'

services:
  
  graphql:
    image: registry.digitalocean.com/fullstack-kea/backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graphql
    ports:
      - "4000:4000"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
      AUTH0_SECRET: ${AUTH0_SECRET}
      AUTH0_BASE_URL: ${AUTH0_BASE_URL}
      AUTH0_ISSUER_BASE_URL: ${AUTH0_ISSUER_BASE_URL}
